"""add_passage_text_to_bundle_contexts

Revision ID: 3fc50b3f7e1e
Revises: 1e6d992cdca0
Create Date: 2026-06-17 22:20:51.546893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc50b3f7e1e'
down_revision = '1e6d992cdca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_contexts', sa.Column('passage_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundle_contexts', 'passage_text')
    # ### end Alembic commands ###
